### ISSUE TITLE
Spaces deleted

### ISSUE THREAD

**Issue by starkadur** [mideind/Tokenizer#21]
When tokenizing ? … the out put is ?…
Is it an expected behaviour of the tokenizer to delete spaces?

**Comment by Holado** [comment]
Hi! At the moment it is, but a large update is in the works that helps to connect individual tokens to the correct span in the original text. When that is ready, which should be soon, I'll look into this. Just wanted to let you know!

**Comment by Holado** [comment]
Support for original versions of tokens, plus original spans, has been added to the Tokenizer.

`echo "Misstirðu dallinn? …" | tokenize --json`

Now returns 

`{"k":"BEGIN SENT","t":""}`
`{"k":"WORD","t":"Misstirðu","o":"Misstirðu","s":[0,1,2,3,4,5,6,7,8]}`
`{"k":"WORD","t":"dallinn","o":" dallinn","s":[1,2,3,4,5,6,7]}`
`{"k":"PUNCTUATION","t":"?…","v":"?","o":"? …","s":[0,2]}`
`{"k":"END SENT","t":""}``

_token.original_ and _token.original_spans_ have been added to the token, and _token.roginal_ contains the original version, which might include spaces before the token.

Does this help?

**Comment by Holado** [comment]
We have added the option -o that resolves this issue.
