### ISSUE TITLE
Adda mánuð

### ISSUE THREAD

**Issue by sigurdurb** [mideind/Tokenizer#37]
Hæ var að fá Keyerror á að það er ekki "maí." með punkti? Er einhver ástæða að það er ekki. Má ég adda því?

https://github.com/mideind/Tokenizer/blob/d020b1d27cf565509eaa6afcd808e85c58793549/src/tokenizer/definitions.py#L250

**Comment by vthorsteinsson** [comment]
Einmitt. En ég held að við breytum þessu ekki hjá okkur, "maí." er villa og ef við settum það inn sem skammstöfun er hætta á að við hættum að þekkja endi málsgreinar sem endar á "maí.", svo sem "Hann á afmæli í maí."
