### ISSUE TITLE
Tokeniize() options

### ISSUE THREAD

**Issue by pallih** [mideind/Tokenizer#4]
Is it worth making the decisions tokenize() makes, optional?

For instance the "kludgy ordinals" conversion..

**Comment by vthorsteinsson** [comment]
Yes, I can see why that could be useful. Probably this should be specified as an optional parameter to `tokenize()`, and for future expandability it could be a `dict`: `tokenize(txt, options=None)` where `options` is a `dict` if present.

**Comment by vthorsteinsson** [comment]
The newest version, 1.4, now has options to control the 'kludgy ordinals' conversion, as well as conversion of numbers and telephone numbers.
