### ISSUE TITLE
A dot added in dates

### ISSUE THREAD

**Issue by starkadur** [mideind/Tokenizer#52]
If I send in "17 júní" the tokenizer returns 17. júní". Even though I use tokenized() (and not split_itsentences()) and use the txt-property (which should contain the original source text for the token) I still get this extra dot.

**Comment by peturorri** [comment]
I think you're looking for the `original` property of the tokens, not `txt`. See: https://github.com/mideind/Tokenizer/blob/master/src/tokenizer/tokenizer.py#L95

**Comment by starkadur** [comment]
Do all tokens have the `original` property? I always get error when trying to access it:
`txt = token.original`
causes an error while 
`txt = token.txt `
does not.

**Comment by peturorri** [comment]
They should all have `original` although it can sometimes be `None`.

Can you provide a complete example of the code you're trying to run, and the version of the `tokenizer` package.

**Comment by starkadur** [comment]
Tokenizer 3.4.3 

The script below takes a string, tokenizes it and splits the output into sentences
```
sent = [] #stores each tokenized sentence
token_list = tokenizer.tokenize(line.strip())
for token in token_list:                
                               
    type_ = tokenizer.TOK.descr[kind]                
    if type_ not in ['BEGIN SENT','END SENT']:
        original = token.original # causes an error  while token.txt does not                 
        sent.append(original)
    elif type_=="END SENT" and len(sent)>0:                 
        output.append(" ".join(sent))
        sent = []
```

**Comment by vthorsteinsson** [comment]
I try the following code:

```
import tokenizer
sent = [] #stores each tokenized sentence
output = []
line = "Ég tók þátt í skrúðgöngu 17 júní en svo hætti ég því. Hins vegar fæ ég mér bjór 1 desember, helst 500ml."
token_list = tokenizer.tokenize(line.strip())
for token in token_list:
    type_ = tokenizer.TOK.descr[token.kind]
    if type_ not in ['BEGIN SENT','END SENT']:
        original = token.original # causes an error  while token.txt does not
        sent.append(original)
    elif type_=="END SENT" and len(sent)>0:
        output.append(" ".join(sent))
        sent = []
print(output)
```

The output is: 

```
villi@brandur:~/github/Tokenizer$ python test.py
['Ég  tók  þátt  í  skrúðgöngu  17 júní  en  svo  hætti  ég  því .', ' Hins  vegar  fæ  ég  mér  bjór  1 desember ,  helst  500ml .']
```

So I fail to reproduce the problem, at least so far.

**Comment by vthorsteinsson** [comment]
```
>>> print(tokenizer.__version__)
3.4.5
```

**Comment by starkadur** [comment]
I realized that the error occurred in the ABLTagger. When using `token.original` the string that is returned contains an extra space at the beginning (" 7 júní") which it does not when using `token.txt`. So the array sent to the tagger had empty  elements which caused the error.
